[package]
name = "waytous"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.0.0", features = ["derive"]}
clap_complete = "4.0.0"
toml = "0.8.0"
serde = {version = "1.0.0", features = ["derive"]}
rusqlite = "0.32.1"
comfy-table = "7.0.0"
colored = "2.0.0"
log = "0.4.22"
